name: Code generation using swagger

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: swaggerapi/swagger-codegen-cli:2.4.27

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Clear AUTOBUILD directory
        run: rm -rf AUTOBUILD

      - name: Generate python client
        run: >
          java
          -jar
          /opt/swagger-codegen-cli/swagger-codegen-cli.jar
          generate
          -i yaml/swagger.yaml
          -l python
          -o AUTOBUILD/pythonBalancerClient/
          -c config/pythonClientConfig.json

      - name: Generate java client
        run: >
          java
          -jar
          /opt/swagger-codegen-cli/swagger-codegen-cli.jar
          generate
          -i yaml/swagger.yaml
          -l java
          -o AUTOBUILD/javaBalancerClient/
          -c config/javaClientConfig.json

      - name: push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Generate code using swagger-codegen'
          files: AUTOBUILD
