name: Code generation using swagger

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: swaggerapi/swagger-codegen-cli:2.4.27

    steps:
      - uses: actions/checkout@v2
      
      - name: Clear AUTOBUILD directory
        run: rm -rf AUTOBUILD

      - name: Generate python client
        run:  >
          swagger-codegen-cli
          generate
          -i yaml/swagger.yaml
          -l python
          -o AUTOBUILD/pythonBalancerClient/
          -c config/pythonClientConfig.json

      - name: Generate java client
        run:  >
          swagger-codegen-cli
          generate
          -i yaml/swagger.yaml
          -l java
          -o AUTOBUILD/javaBalancerClient/
          -c config/javaClientConfig.json

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Regenerate the clients and server stub
            file_pattern: AUTOBUILD/
