name: Code generation using swagger

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: swaggerapi/swagger-codegen-cli:2.4.27

    steps:
      - uses: actions/checkout@v2

      - name: Debug print
        run: find .

      - name: Clear AUTOBUILD directory
        run: rm -rf AUTOBUILD

      - name: Debug print
        run: find .

      - name: Generate python client
        run: >
          java
          -jar
          /opt/swagger-codegen-cli/swagger-codegen-cli.jar
          generate
          -i yaml/swagger.yaml
          -l python
          -o AUTOBUILD/pythonBalancerClient/
          -c config/pythonClientConfig.json

      - name: Debug print
        run: find .

      - name: Generate java client
        run: >
          java
          -jar
          /opt/swagger-codegen-cli/swagger-codegen-cli.jar
          generate
          -i yaml/swagger.yaml
          -l java
          -o AUTOBUILD/javaBalancerClient/
          -c config/javaClientConfig.json

      - name: Debug print
        run: find .

      - name: Push changes to the repository
        uses: actions-x/commit@v6
        with:
          message: 'Generate code using swagger-codegen'
